import 'dart:convert';
import 'dart:developer';


import 'package:http/http.dart' as http;
import 'package:zizzia_e_commerce/controller/hive/storing.dart';
import 'package:zizzia_e_commerce/ip/ip.dart';
import 'package:zizzia_e_commerce/model/profileView.dart';

class ProfileApi {
  Future<Autogenerated> profilePageApi() async {
    try {
      final token = await tokenGet();
      final uri = Uri.parse("http://${ip}:3000/flutter/profile");

      final response = await http.get(
        uri,
        headers: {
          'Authorization': 'Bearer $token',
          'Content-Type': 'application/json; charset=UTF-8',
        },
      );

      // log('Response Status Code: ${response.statusCode}');

      if (response.statusCode == 200) {
        // log('${response.body}');
      
      
        return Autogenerated.fromJson(json.decode(response.body));
      } else {
        throw Exception("Request failed with status: ${response.statusCode}");
      }
    } 
    catch (e, stackTrace) {
      // log('Exception: $e', error: e, stackTrace: stackTrace);
      rethrow; // Rethrow the exception to propagate it to the caller
    }
  }
}



